@startuml setiup
left to right direction
title Use Cases - Setup
actor Guest as guest
package webapp {
  usecase "Set up Client" as SetUpClient
  usecase "Set up Server" as SetUpServer
}

guest --> SetUpClient
guest --> SetUpServer
@enduml
