@startuml Setup Client/Server
title Setup Client/Server
actor Guest
autonumber 1.1
Guest -> Server: Launch HTTP Server
Server --> Guest: Fiber v2.52.4 
note right
 http://127.0.0.1:8080
end note
Guest -> Client: Launch HTTP Client
Client --> Guest: Browser Tab Show Landing Page
note right
 any Browser will do
end note
@enduml